export function GetLanguageOptions(): { data: string; label: string }[] {
  return Object.keys(LOCALIZATION).map((key) => ({
    data: key,
    label: LOCALIZATION[key as keyof typeof LOCALIZATION].languageName,
  }));
}

export function Localize(language: string, key: string): string {
  try {
    const localization = LOCALIZATION as Record<string, Record<string, string>>;
    return localization[language]?.[key] ?? localization.English?.[key] ?? key;
  } catch {
    return key;
  }
}

const LOCALIZATION = {
    "English": {
        "languageName": "English",
        "LanguageOfPlugin": "Language of plugin",
        "SaveSettings": "Save settings",
        "GameNameParameterTip": "For button sections marked with * sign, the %GAME_NAME% parameter can be used in the button name and URL. It will be replaced to the name of the game for which the button was called. For example: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "The name that will be displayed on the button",
        "ButtonShowNameTip": "Should the button's name be shown on it?",
        "ButtonIconTip": "URL of the icon that will be displayed on the button",
        "ButtonShowIconTip": "Should the button's icon be shown on it?",
        "ButtonPathToAppTip": "The URL or App Path (e.g., https://www.example.com or C:\\Program Files\\App\\app.exe) to open when the button is clicked",
        "ButtonFormatGameNameTip": "Does the game name need to be formatted when it is inserted into a parameter %GAME_NAME%. Formatting replaces spaces and slashes with + signs, which is convenient for opening URLs in a browser.",
        "ButtonAddArrowIconTip": "Whether to add an arrow icon to the button",
        "DropdownMenuSettings": "Dropdown Menu Settings",
        "Right click on game context menu buttons": "Right click on game context menu buttons",
        "Add right click on game context menu button": "Add right click on game context menu button",
        "FormatGameName": "Format game name",
        "AddArrowIcon": "Add arrow icon",
        "URL or App Path": "URL or App Path",
        "delete this button": "delete this button",
        "Add Button": "Add button",
        "EnableButton": "Enable button",
        "EnableButtonTip": "If disabled, this button will not be added to the Steam interface",
        "ImportSettings": "Import settings",
        "ImportSettingsTip": "Load all settings from a previously exported JSON file",
        "ExportSettings": "Export settings",
        "ExportSettingsTip": "Save all current settings to a JSON file",
        "ResetSettings": "Reset settings",
        "ResetSettingsTip": "Reset all settings to their default values",
        "Confirm": "Confirm",
        "Cancel": "Cancel",
        "ConfirmDeleteButtonTitle": "Confirm deletion",
        "ConfirmDeleteButtonDescription": "Are you sure you want to delete button %BUTTON_NUMBER% '%BUTTON_NAME%'? This action cannot be undone.",
        "ConfirmResetSettingsTitle": "Confirm settings reset",
        "ConfirmResetSettingsDescription": "Are you sure you want to reset all settings to default? All your buttons will be replaced with the default set. This action cannot be undone.",
        "ConfirmImportSettingsTitle": "Confirm settings import",
        "ConfirmImportSettingsDescription": "Are you sure you want to import settings from the selected file? All your current buttons will be replaced. This action cannot be undone.",
        "ImportSettingsError": "Failed to import settings: the file is not a valid settings file",
        "SettingsAreSavedAutomatically": "All changes are saved automatically",
        "GameIdCache": "Game ID cache",
        "ClearGameIdCache": "Clear game ID cache",
        "ClearGameIdCacheTip": "Delete all cached game IDs. They will be requested from Steam again when a button with the %GAME_ID% parameter is used",
        "GameIdParameterTip": "The %GAME_ID% parameter can be used the same way as %GAME_NAME%. It is replaced with the Steam ID of the game for which the button was called. For example: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. The ID is requested from Steam once for each game and then cached. Because of that request, the first click of such a button may take a moment.",
        "Top Buttons style": "Top Buttons style",
        "Top Buttons style changer description": "CSS style for the top buttons. You can copy it to another editor, modify it as you wish, and paste it back here.",
        "SettingsSavedSuccessfully": "Settings saved successfully!",
        "Name": "Name",
        "Button Number": "Button Number",
        "Name for the drop-down menu section": "Name for the drop-down menu section",
        "Append after": "Append after",
        "After which element should the menu be inserted": "After which element (by number) should a drop-down menu with custom buttons be inserted",
        "Right click on game context menu buttons in drop down": "Right click on game context menu buttons in drop down",
        "Add right click on game context menu button in drop down": "Add right click on game context menu button in drop down",
        "Game properties menu buttons": "Game properties menu buttons",
        "Add game properties menu buttons": "Add game properties menu buttons",
        "Top Buttons": "Top Buttons",
        "Show name": "Show name",
        "Icon": "Icon",
        "Show icon": "Show icon",
        "Add top button": "Add top button",
        "Store supernav buttons": "Buttons in the 'Store' menu (Store supernav)",
        "Add store supernav buttons": "Add button to the 'Store' menu (Store supernav)",
        "App page Buttons": "App page Buttons",
        "Add app page button": "Add app page button"
    },
    "Russian": {
        "languageName": "Русский",
        "LanguageOfPlugin": "Язык плагина",
        "SaveSettings": "Сохранить настройки",
        "GameNameParameterTip": "Для секций кнопок, отмеченных знаком *, параметр %GAME_NAME% можно использовать в названии кнопки и URL. Он будет заменен на название игры, для которой была вызвана кнопка. Например: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "Название, которое будет отображаться на кнопке",
        "ButtonShowNameTip": "Показывать название кнопки?",
        "ButtonIconTip": "URL иконки, которая будет отображаться на кнопке",
        "ButtonShowIconTip": "Показывать иконку кнопки?",
        "ButtonPathToAppTip": "URL или путь к приложению (например, https://www.example.com или C:\\Program Files\\App\\app.exe), который открывается при нажатии кнопки",
        "ButtonFormatGameNameTip": "Нужно ли форматировать название игры при вставке в параметр %GAME_NAME%. Форматирование заменяет пробелы и слеши на символ +, что удобно для открытия URL в браузере.",
        "ButtonAddArrowIconTip": "Добавлять иконку стрелку к кнопке",
        "DropdownMenuSettings": "Настройки выпадающего меню",
        "Right click on game context menu buttons": "Кнопки контекстного меню при правом клике на игру",
        "Add right click on game context menu button": "Добавить кнопку контекстного меню при правом клике на игру",
        "FormatGameName": "Форматировать название игры",
        "AddArrowIcon": "Добавить иконку стрелки",
        "URL or App Path": "URL или путь к приложению",
        "delete this button": "Удалить эту кнопку",
        "Add Button": "Добавить кнопку",
        "EnableButton": "Включить кнопку",
        "EnableButtonTip": "Если выключено, кнопка не будет добавляться в интерфейс Steam",
        "ImportSettings": "Импорт настроек",
        "ImportSettingsTip": "Загрузить все настройки из ранее экспортированного JSON файла",
        "ExportSettings": "Экспорт настроек",
        "ExportSettingsTip": "Сохранить все текущие настройки в JSON файл",
        "ResetSettings": "Сброс настроек",
        "ResetSettingsTip": "Сбросить все настройки к значениям по умолчанию",
        "Confirm": "Подтвердить",
        "Cancel": "Отмена",
        "ConfirmDeleteButtonTitle": "Подтвердите удаление",
        "ConfirmDeleteButtonDescription": "Вы уверены, что хотите удалить кнопку %BUTTON_NUMBER% «%BUTTON_NAME%»? Это действие нельзя отменить.",
        "ConfirmResetSettingsTitle": "Подтвердите сброс настроек",
        "ConfirmResetSettingsDescription": "Вы уверены, что хотите сбросить все настройки к значениям по умолчанию? Все ваши кнопки будут заменены стандартным набором. Это действие нельзя отменить.",
        "ConfirmImportSettingsTitle": "Подтвердите импорт настроек",
        "ConfirmImportSettingsDescription": "Вы уверены, что хотите импортировать настройки из выбранного файла? Все ваши текущие кнопки будут заменены. Это действие нельзя отменить.",
        "ImportSettingsError": "Не удалось импортировать настройки: файл не является корректным файлом настроек",
        "SettingsAreSavedAutomatically": "Все изменения сохраняются автоматически",
        "GameIdCache": "Кэш ID игр",
        "ClearGameIdCache": "Очистить кэш ID игр",
        "ClearGameIdCacheTip": "Удалить все закэшированные ID игр. Они будут запрошены у Steam заново при использовании кнопки с параметром %GAME_ID%",
        "GameIdParameterTip": "Параметр %GAME_ID% можно использовать так же, как и %GAME_NAME%. Он заменяется на Steam ID игры, для которой была вызвана кнопка. Например: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. ID запрашивается у Steam один раз для каждой игры и затем кэшируется. Из-за этого запроса первое нажатие такой кнопки может сработать не сразу.",
        "Top Buttons style": "Стиль верхних кнопок",
        "Top Buttons style changer description": "CSS стиль для верхних кнопок. Вы можете скопировать его в другой редактор, изменить по своему усмотрению и вставить обратно сюда.",
        "SettingsSavedSuccessfully": "Настройки успешно сохранены!",
        "Name": "Имя",
        "Button Number": "Номер кнопки",
        "Name for the drop-down menu section": "Имя для секции выпадающего меню",
        "Append after": "Вставить после",
        "After which element should the menu be inserted": "После какого элемента (по номеру) должно быть вставлено выпадающее меню с кастомными кнопками",
        "Right click on game context menu buttons in drop down": "Кнопки контекстного меню при правом клике на игру в выпадающем меню",
        "Add right click on game context menu button in drop down": "Добавить кнопку контекстного меню при правом клике в выпадающее меню",
        "Game properties menu buttons": "Кнопки меню свойств игры",
        "Add game properties menu buttons": "Добавить кнопку в меню свойств игры",
        "Top Buttons": "Верхние кнопки",
        "Show name": "Показывать имя",
        "Icon": "Иконка",
        "Show icon": "Показывать иконку",
        "Add top button": "Добавить верхнюю кнопку",
        "Store supernav buttons": "Кнопки в меню 'Магазин' (Store supernav)",
        "Add store supernav buttons": "Добавить кнопку в меню 'Магазин' (Store supernav)",
        "App page Buttons": "Кнопки на странице игры",
        "Add app page button": "Добавить кнопку на страницу игры"
      },
    "ChineseSimplified": {
        "languageName": "简体中文",
        "LanguageOfPlugin": "插件语言",
        "SaveSettings": "保存设置",
        "GameNameParameterTip": "对于带有 * 标记的按钮分组，%GAME_NAME% 参数可用于按钮名称和 URL。它会被替换为触发该按钮时的游戏名称。例如：https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "将显示在按钮上的名称",
        "ButtonShowNameTip": "是否显示按钮名称？",
        "ButtonIconTip": "将显示在按钮上的图标 URL",
        "ButtonShowIconTip": "是否显示按钮图标？",
        "ButtonPathToAppTip": "点击按钮时要打开的 URL 或应用路径（例如：https://www.example.com 或 C:\\Program Files\\App\\app.exe）",
        "ButtonFormatGameNameTip": "将游戏名称插入 %GAME_NAME% 参数时是否需要格式化。格式化会将空格和斜杠替换为 +，便于在浏览器中打开 URL。",
        "ButtonAddArrowIconTip": "是否为按钮添加箭头图标",
        "DropdownMenuSettings": "下拉菜单设置",
        "Right click on game context menu buttons": "游戏右键菜单按钮",
        "Add right click on game context menu button": "添加游戏右键菜单按钮",
        "FormatGameName": "格式化游戏名称",
        "AddArrowIcon": "添加箭头图标",
        "URL or App Path": "URL 或应用路径",
        "delete this button": "删除此按钮",
        "Add Button": "添加按钮",
        "EnableButton": "启用按钮",
        "EnableButtonTip": "如果禁用，此按钮将不会添加到 Steam 界面中",
        "ImportSettings": "导入设置",
        "ImportSettingsTip": "从之前导出的 JSON 文件中加载所有设置",
        "ExportSettings": "导出设置",
        "ExportSettingsTip": "将当前所有设置保存为 JSON 文件",
        "ResetSettings": "重置设置",
        "ResetSettingsTip": "将所有设置恢复为默认值",
        "Confirm": "确认",
        "Cancel": "取消",
        "ConfirmDeleteButtonTitle": "确认删除",
        "ConfirmDeleteButtonDescription": "确定要删除按钮 %BUTTON_NUMBER%“%BUTTON_NAME%”吗？此操作无法撤销。",
        "ConfirmResetSettingsTitle": "确认重置设置",
        "ConfirmResetSettingsDescription": "确定要将所有设置重置为默认值吗？你的所有按钮将被默认设置替换。此操作无法撤销。",
        "ConfirmImportSettingsTitle": "确认导入设置",
        "ConfirmImportSettingsDescription": "确定要从所选文件导入设置吗？你当前的所有按钮都将被替换。此操作无法撤销。",
        "ImportSettingsError": "导入设置失败：该文件不是有效的设置文件",
        "SettingsAreSavedAutomatically": "所有更改都会自动保存",
        "GameIdCache": "游戏 ID 缓存",
        "ClearGameIdCache": "清除游戏 ID 缓存",
        "ClearGameIdCacheTip": "删除所有已缓存的游戏 ID。当使用带 %GAME_ID% 参数的按钮时将重新向 Steam 请求",
        "GameIdParameterTip": "%GAME_ID% 参数的用法与 %GAME_NAME% 相同。它会被替换为触发该按钮的游戏的 Steam ID。例如：https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/。每个游戏的 ID 只会向 Steam 请求一次，之后会被缓存。 因此，此类按钮的第一次点击可能不会立即生效。",
        "Top Buttons style": "顶部按钮样式",
        "Top Buttons style changer description": "顶部按钮的 CSS 样式。你可以复制到其他编辑器进行修改，然后粘贴回这里。",
        "SettingsSavedSuccessfully": "设置已成功保存！",
        "Name": "名称",
        "Button Number": "按钮编号",
        "Name for the drop-down menu section": "下拉菜单分组名称",
        "Append after": "插入到其后",
        "After which element should the menu be inserted": "应在第几个元素后插入带有自定义按钮的下拉菜单",
        "Right click on game context menu buttons in drop down": "下拉菜单中的游戏右键菜单按钮",
        "Add right click on game context menu button in drop down": "在下拉菜单中添加游戏右键菜单按钮",
        "Game properties menu buttons": "游戏属性菜单按钮",
        "Add game properties menu buttons": "添加游戏属性菜单按钮",
        "Top Buttons": "顶部按钮",
        "Show name": "显示名称",
        "Icon": "图标",
        "Show icon": "显示图标",
        "Add top button": "添加顶部按钮",
        "Store supernav buttons": "“商店”菜单中的按钮（Store supernav）",
        "Add store supernav buttons": "在“商店”菜单（Store supernav）中添加按钮",
        "App page Buttons": "游戏页面按钮",
        "Add app page button": "添加游戏页面按钮"
      },
    "Spanish": {
        "languageName": "Español",
        "LanguageOfPlugin": "Idioma del plugin",
        "SaveSettings": "Guardar ajustes",
        "GameNameParameterTip": "En las secciones de botones marcadas con *, el parámetro %GAME_NAME% puede usarse en el nombre del botón y en la URL. Se reemplazará por el nombre del juego para el que se llamó el botón. Por ejemplo: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "El nombre que se mostrará en el botón",
        "ButtonShowNameTip": "¿Mostrar el nombre del botón?",
        "ButtonIconTip": "URL del icono que se mostrará en el botón",
        "ButtonShowIconTip": "¿Mostrar el icono del botón?",
        "ButtonPathToAppTip": "La URL o ruta de la app (por ejemplo, https://www.example.com o C:\\Program Files\\App\\app.exe) que se abrirá al hacer clic en el botón",
        "ButtonFormatGameNameTip": "¿Es necesario formatear el nombre del juego al insertarlo en %GAME_NAME%? El formateo reemplaza espacios y barras con +, lo cual es conveniente para abrir URL en el navegador.",
        "ButtonAddArrowIconTip": "Si se debe agregar un icono de flecha al botón",
        "DropdownMenuSettings": "Ajustes del menú desplegable",
        "Right click on game context menu buttons": "Botones del menú contextual con clic derecho en juego",
        "Add right click on game context menu button": "Agregar botón al menú contextual con clic derecho en juego",
        "FormatGameName": "Formatear nombre del juego",
        "AddArrowIcon": "Agregar icono de flecha",
        "URL or App Path": "URL o ruta de la app",
        "delete this button": "eliminar este botón",
        "Add Button": "Agregar botón",
        "EnableButton": "Activar botón",
        "EnableButtonTip": "Si está desactivado, este botón no se agregará a la interfaz de Steam",
        "ImportSettings": "Importar ajustes",
        "ImportSettingsTip": "Cargar todos los ajustes desde un archivo JSON exportado previamente",
        "ExportSettings": "Exportar ajustes",
        "ExportSettingsTip": "Guardar todos los ajustes actuales en un archivo JSON",
        "ResetSettings": "Restablecer ajustes",
        "ResetSettingsTip": "Restablecer todos los ajustes a sus valores predeterminados",
        "Confirm": "Confirmar",
        "Cancel": "Cancelar",
        "ConfirmDeleteButtonTitle": "Confirmar eliminación",
        "ConfirmDeleteButtonDescription": "¿Seguro que quieres eliminar el botón %BUTTON_NUMBER% «%BUTTON_NAME%»? Esta acción no se puede deshacer.",
        "ConfirmResetSettingsTitle": "Confirmar restablecimiento",
        "ConfirmResetSettingsDescription": "¿Seguro que quieres restablecer todos los ajustes a los valores predeterminados? Todos tus botones serán reemplazados por el conjunto predeterminado. Esta acción no se puede deshacer.",
        "ConfirmImportSettingsTitle": "Confirmar importación",
        "ConfirmImportSettingsDescription": "¿Seguro que quieres importar los ajustes del archivo seleccionado? Todos tus botones actuales serán reemplazados. Esta acción no se puede deshacer.",
        "ImportSettingsError": "No se pudieron importar los ajustes: el archivo no es un archivo de ajustes válido",
        "SettingsAreSavedAutomatically": "Todos los cambios se guardan automáticamente",
        "GameIdCache": "Caché de ID de juegos",
        "ClearGameIdCache": "Borrar caché de ID de juegos",
        "ClearGameIdCacheTip": "Eliminar todos los ID de juegos en caché. Se volverán a solicitar a Steam cuando se use un botón con el parámetro %GAME_ID%",
        "GameIdParameterTip": "El parámetro %GAME_ID% se puede usar igual que %GAME_NAME%. Se reemplaza por el ID de Steam del juego para el que se llamó el botón. Por ejemplo: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. El ID se solicita a Steam una vez por juego y luego se guarda en caché. Por esa petición, el primer clic en ese botón puede tardar un momento.",
        "Top Buttons style": "Estilo de botones superiores",
        "Top Buttons style changer description": "Estilo CSS para los botones superiores. Puedes copiarlo a otro editor, modificarlo como quieras y pegarlo aquí de nuevo.",
        "SettingsSavedSuccessfully": "¡Ajustes guardados correctamente!",
        "Name": "Nombre",
        "Button Number": "Número de botón",
        "Name for the drop-down menu section": "Nombre para la sección del menú desplegable",
        "Append after": "Insertar después de",
        "After which element should the menu be inserted": "Después de qué elemento (por número) se debe insertar el menú desplegable con botones personalizados",
        "Right click on game context menu buttons in drop down": "Botones del menú contextual con clic derecho en juego dentro del desplegable",
        "Add right click on game context menu button in drop down": "Agregar botón de clic derecho en juego dentro del desplegable",
        "Game properties menu buttons": "Botones del menú de propiedades del juego",
        "Add game properties menu buttons": "Agregar botones al menú de propiedades del juego",
        "Top Buttons": "Botones superiores",
        "Show name": "Mostrar nombre",
        "Icon": "Icono",
        "Show icon": "Mostrar icono",
        "Add top button": "Agregar botón superior",
        "Store supernav buttons": "Botones en el menú 'Tienda' (Store supernav)",
        "Add store supernav buttons": "Agregar botón al menú 'Tienda' (Store supernav)",
        "App page Buttons": "Botones de la página del juego",
        "Add app page button": "Agregar botón a la página del juego"
      },
    "PortugueseBrazil": {
        "languageName": "Português (Brasil)",
        "LanguageOfPlugin": "Idioma do plugin",
        "SaveSettings": "Salvar configurações",
        "GameNameParameterTip": "Para seções de botões marcadas com *, o parâmetro %GAME_NAME% pode ser usado no nome do botão e na URL. Ele será substituído pelo nome do jogo para o qual o botão foi chamado. Exemplo: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "O nome que será exibido no botão",
        "ButtonShowNameTip": "Mostrar o nome do botão?",
        "ButtonIconTip": "URL do ícone que será exibido no botão",
        "ButtonShowIconTip": "Mostrar o ícone do botão?",
        "ButtonPathToAppTip": "A URL ou caminho do app (por exemplo, https://www.example.com ou C:\\Program Files\\App\\app.exe) a ser aberto ao clicar no botão",
        "ButtonFormatGameNameTip": "É necessário formatar o nome do jogo ao inseri-lo no parâmetro %GAME_NAME%? A formatação substitui espaços e barras por +, o que é conveniente para abrir URLs no navegador.",
        "ButtonAddArrowIconTip": "Se deve adicionar um ícone de seta ao botão",
        "DropdownMenuSettings": "Configurações do menu suspenso",
        "Right click on game context menu buttons": "Botões do menu de contexto ao clicar com o botão direito no jogo",
        "Add right click on game context menu button": "Adicionar botão ao menu de contexto com clique direito no jogo",
        "FormatGameName": "Formatar nome do jogo",
        "AddArrowIcon": "Adicionar ícone de seta",
        "URL or App Path": "URL ou caminho do app",
        "delete this button": "excluir este botão",
        "Add Button": "Adicionar botão",
        "EnableButton": "Ativar botão",
        "EnableButtonTip": "Se desativado, este botão não será adicionado à interface do Steam",
        "ImportSettings": "Importar configurações",
        "ImportSettingsTip": "Carregar todas as configurações de um arquivo JSON exportado anteriormente",
        "ExportSettings": "Exportar configurações",
        "ExportSettingsTip": "Salvar todas as configurações atuais em um arquivo JSON",
        "ResetSettings": "Redefinir configurações",
        "ResetSettingsTip": "Redefinir todas as configurações para os valores padrão",
        "Confirm": "Confirmar",
        "Cancel": "Cancelar",
        "ConfirmDeleteButtonTitle": "Confirmar exclusão",
        "ConfirmDeleteButtonDescription": "Tem certeza de que deseja excluir o botão %BUTTON_NUMBER% '%BUTTON_NAME%'? Esta ação não pode ser desfeita.",
        "ConfirmResetSettingsTitle": "Confirmar redefinição",
        "ConfirmResetSettingsDescription": "Tem certeza de que deseja redefinir todas as configurações para o padrão? Todos os seus botões serão substituídos pelo conjunto padrão. Esta ação não pode ser desfeita.",
        "ConfirmImportSettingsTitle": "Confirmar importação",
        "ConfirmImportSettingsDescription": "Tem certeza de que deseja importar as configurações do arquivo selecionado? Todos os seus botões atuais serão substituídos. Esta ação não pode ser desfeita.",
        "ImportSettingsError": "Falha ao importar configurações: o arquivo não é um arquivo de configurações válido",
        "SettingsAreSavedAutomatically": "Todas as alterações são salvas automaticamente",
        "GameIdCache": "Cache de IDs de jogos",
        "ClearGameIdCache": "Limpar cache de IDs de jogos",
        "ClearGameIdCacheTip": "Excluir todos os IDs de jogos em cache. Eles serão solicitados ao Steam novamente ao usar um botão com o parâmetro %GAME_ID%",
        "GameIdParameterTip": "O parâmetro %GAME_ID% pode ser usado da mesma forma que %GAME_NAME%. Ele é substituído pelo ID do Steam do jogo para o qual o botão foi chamado. Exemplo: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. O ID é solicitado ao Steam uma vez por jogo e depois armazenado em cache. Por causa dessa requisição, o primeiro clique nesse botão pode demorar um instante.",
        "Top Buttons style": "Estilo dos botões superiores",
        "Top Buttons style changer description": "Estilo CSS para os botões superiores. Você pode copiar para outro editor, modificar como quiser e colar de volta aqui.",
        "SettingsSavedSuccessfully": "Configurações salvas com sucesso!",
        "Name": "Nome",
        "Button Number": "Número do botão",
        "Name for the drop-down menu section": "Nome da seção do menu suspenso",
        "Append after": "Inserir após",
        "After which element should the menu be inserted": "Após qual elemento (por número) deve ser inserido o menu suspenso com botões personalizados",
        "Right click on game context menu buttons in drop down": "Botões do menu de contexto com clique direito no jogo dentro do menu suspenso",
        "Add right click on game context menu button in drop down": "Adicionar botão de clique direito no jogo dentro do menu suspenso",
        "Game properties menu buttons": "Botões do menu de propriedades do jogo",
        "Add game properties menu buttons": "Adicionar botões ao menu de propriedades do jogo",
        "Top Buttons": "Botões superiores",
        "Show name": "Mostrar nome",
        "Icon": "Ícone",
        "Show icon": "Mostrar ícone",
        "Add top button": "Adicionar botão superior",
        "Store supernav buttons": "Botões no menu 'Loja' (Store supernav)",
        "Add store supernav buttons": "Adicionar botão ao menu 'Loja' (Store supernav)",
        "App page Buttons": "Botões da página do jogo",
        "Add app page button": "Adicionar botão à página do jogo"
      },
    "German": {
        "languageName": "Deutsch",
        "LanguageOfPlugin": "Plugin-Sprache",
        "SaveSettings": "Einstellungen speichern",
        "GameNameParameterTip": "Für Button-Bereiche mit * kann der Parameter %GAME_NAME% im Button-Namen und in der URL verwendet werden. Er wird durch den Namen des Spiels ersetzt, für das der Button aufgerufen wurde. Beispiel: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "Der Name, der auf dem Button angezeigt wird",
        "ButtonShowNameTip": "Soll der Button-Name angezeigt werden?",
        "ButtonIconTip": "URL des Symbols, das auf dem Button angezeigt wird",
        "ButtonShowIconTip": "Soll das Button-Symbol angezeigt werden?",
        "ButtonPathToAppTip": "Die URL oder der App-Pfad (z. B. https://www.example.com oder C:\\Program Files\\App\\app.exe), der beim Klick auf den Button geöffnet wird",
        "ButtonFormatGameNameTip": "Soll der Spielname beim Einfügen in den Parameter %GAME_NAME% formatiert werden? Die Formatierung ersetzt Leerzeichen und Schrägstriche durch +, was für das Öffnen von URLs im Browser praktisch ist.",
        "ButtonAddArrowIconTip": "Ob dem Button ein Pfeilsymbol hinzugefügt werden soll",
        "DropdownMenuSettings": "Dropdown-Menü-Einstellungen",
        "Right click on game context menu buttons": "Buttons im Kontextmenü bei Rechtsklick auf ein Spiel",
        "Add right click on game context menu button": "Button zum Kontextmenü bei Rechtsklick auf ein Spiel hinzufügen",
        "FormatGameName": "Spielnamen formatieren",
        "AddArrowIcon": "Pfeilsymbol hinzufügen",
        "URL or App Path": "URL oder App-Pfad",
        "delete this button": "diesen Button löschen",
        "Add Button": "Button hinzufügen",
        "EnableButton": "Button aktivieren",
        "EnableButtonTip": "Wenn deaktiviert, wird dieser Button nicht zur Steam-Oberfläche hinzugefügt",
        "ImportSettings": "Einstellungen importieren",
        "ImportSettingsTip": "Alle Einstellungen aus einer zuvor exportierten JSON-Datei laden",
        "ExportSettings": "Einstellungen exportieren",
        "ExportSettingsTip": "Alle aktuellen Einstellungen in einer JSON-Datei speichern",
        "ResetSettings": "Einstellungen zurücksetzen",
        "ResetSettingsTip": "Alle Einstellungen auf die Standardwerte zurücksetzen",
        "Confirm": "Bestätigen",
        "Cancel": "Abbrechen",
        "ConfirmDeleteButtonTitle": "Löschen bestätigen",
        "ConfirmDeleteButtonDescription": "Möchtest du den Button %BUTTON_NUMBER% „%BUTTON_NAME%“ wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
        "ConfirmResetSettingsTitle": "Zurücksetzen bestätigen",
        "ConfirmResetSettingsDescription": "Möchtest du wirklich alle Einstellungen auf die Standardwerte zurücksetzen? Alle deine Buttons werden durch den Standardsatz ersetzt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "ConfirmImportSettingsTitle": "Import bestätigen",
        "ConfirmImportSettingsDescription": "Möchtest du die Einstellungen wirklich aus der ausgewählten Datei importieren? Alle deine aktuellen Buttons werden ersetzt. Diese Aktion kann nicht rückgängig gemacht werden.",
        "ImportSettingsError": "Einstellungen konnten nicht importiert werden: Die Datei ist keine gültige Einstellungsdatei",
        "SettingsAreSavedAutomatically": "Alle Änderungen werden automatisch gespeichert",
        "GameIdCache": "Spiel-ID-Cache",
        "ClearGameIdCache": "Spiel-ID-Cache leeren",
        "ClearGameIdCacheTip": "Alle zwischengespeicherten Spiel-IDs löschen. Sie werden erneut von Steam abgerufen, wenn ein Button mit dem Parameter %GAME_ID% verwendet wird",
        "GameIdParameterTip": "Der Parameter %GAME_ID% kann genauso wie %GAME_NAME% verwendet werden. Er wird durch die Steam-ID des Spiels ersetzt, für das der Button aufgerufen wurde. Beispiel: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. Die ID wird einmal pro Spiel von Steam abgerufen und dann zwischengespeichert. Wegen dieser Anfrage kann der erste Klick auf einen solchen Button einen Moment dauern.",
        "Top Buttons style": "Stil der oberen Buttons",
        "Top Buttons style changer description": "CSS-Stil für die oberen Buttons. Du kannst ihn in einen anderen Editor kopieren, beliebig ändern und hier wieder einfügen.",
        "SettingsSavedSuccessfully": "Einstellungen erfolgreich gespeichert!",
        "Name": "Name",
        "Button Number": "Button-Nummer",
        "Name for the drop-down menu section": "Name für den Dropdown-Menübereich",
        "Append after": "Einfügen nach",
        "After which element should the menu be inserted": "Nach welchem Element (nach Nummer) soll das Dropdown-Menü mit benutzerdefinierten Buttons eingefügt werden",
        "Right click on game context menu buttons in drop down": "Kontextmenü-Buttons bei Rechtsklick auf ein Spiel im Dropdown-Menü",
        "Add right click on game context menu button in drop down": "Kontextmenü-Button für Rechtsklick auf ein Spiel im Dropdown-Menü hinzufügen",
        "Game properties menu buttons": "Buttons im Eigenschaftenmenü des Spiels",
        "Add game properties menu buttons": "Buttons zum Eigenschaftenmenü des Spiels hinzufügen",
        "Top Buttons": "Obere Buttons",
        "Show name": "Name anzeigen",
        "Icon": "Symbol",
        "Show icon": "Symbol anzeigen",
        "Add top button": "Oberen Button hinzufügen",
        "Store supernav buttons": "Buttons im Menü 'Shop' (Store supernav)",
        "Add store supernav buttons": "Button zum Menü 'Shop' (Store supernav) hinzufügen",
        "App page Buttons": "Buttons auf der Spielseite",
        "Add app page button": "Button zur Spielseite hinzufügen"
      },
    "French": {
        "languageName": "Français",
        "LanguageOfPlugin": "Langue du plugin",
        "SaveSettings": "Enregistrer les paramètres",
        "GameNameParameterTip": "Pour les sections de boutons marquées par *, le paramètre %GAME_NAME% peut être utilisé dans le nom du bouton et l'URL. Il sera remplacé par le nom du jeu pour lequel le bouton a été appelé. Exemple : https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "Le nom qui sera affiché sur le bouton",
        "ButtonShowNameTip": "Afficher le nom du bouton ?",
        "ButtonIconTip": "URL de l'icône qui sera affichée sur le bouton",
        "ButtonShowIconTip": "Afficher l'icône du bouton ?",
        "ButtonPathToAppTip": "L'URL ou le chemin de l'application (par ex. https://www.example.com ou C:\\Program Files\\App\\app.exe) à ouvrir lors du clic sur le bouton",
        "ButtonFormatGameNameTip": "Faut-il formater le nom du jeu lors de son insertion dans le paramètre %GAME_NAME% ? Le formatage remplace les espaces et les slashs par +, ce qui est pratique pour ouvrir des URL dans le navigateur.",
        "ButtonAddArrowIconTip": "S'il faut ajouter une icône de flèche au bouton",
        "DropdownMenuSettings": "Paramètres du menu déroulant",
        "Right click on game context menu buttons": "Boutons du menu contextuel au clic droit sur un jeu",
        "Add right click on game context menu button": "Ajouter un bouton au menu contextuel au clic droit sur un jeu",
        "FormatGameName": "Formater le nom du jeu",
        "AddArrowIcon": "Ajouter une icône de flèche",
        "URL or App Path": "URL ou chemin de l'application",
        "delete this button": "supprimer ce bouton",
        "Add Button": "Ajouter un bouton",
        "EnableButton": "Activer le bouton",
        "EnableButtonTip": "Si désactivé, ce bouton ne sera pas ajouté à l'interface de Steam",
        "ImportSettings": "Importer les paramètres",
        "ImportSettingsTip": "Charger tous les paramètres depuis un fichier JSON exporté précédemment",
        "ExportSettings": "Exporter les paramètres",
        "ExportSettingsTip": "Enregistrer tous les paramètres actuels dans un fichier JSON",
        "ResetSettings": "Réinitialiser les paramètres",
        "ResetSettingsTip": "Réinitialiser tous les paramètres à leurs valeurs par défaut",
        "Confirm": "Confirmer",
        "Cancel": "Annuler",
        "ConfirmDeleteButtonTitle": "Confirmer la suppression",
        "ConfirmDeleteButtonDescription": "Voulez-vous vraiment supprimer le bouton %BUTTON_NUMBER% « %BUTTON_NAME% » ? Cette action est irréversible.",
        "ConfirmResetSettingsTitle": "Confirmer la réinitialisation",
        "ConfirmResetSettingsDescription": "Voulez-vous vraiment réinitialiser tous les paramètres aux valeurs par défaut ? Tous vos boutons seront remplacés par l'ensemble par défaut. Cette action est irréversible.",
        "ConfirmImportSettingsTitle": "Confirmer l'importation",
        "ConfirmImportSettingsDescription": "Voulez-vous vraiment importer les paramètres du fichier sélectionné ? Tous vos boutons actuels seront remplacés. Cette action est irréversible.",
        "ImportSettingsError": "Échec de l'importation des paramètres : le fichier n'est pas un fichier de paramètres valide",
        "SettingsAreSavedAutomatically": "Toutes les modifications sont enregistrées automatiquement",
        "GameIdCache": "Cache des ID de jeux",
        "ClearGameIdCache": "Vider le cache des ID de jeux",
        "ClearGameIdCacheTip": "Supprimer tous les ID de jeux mis en cache. Ils seront à nouveau demandés à Steam lors de l'utilisation d'un bouton avec le paramètre %GAME_ID%",
        "GameIdParameterTip": "Le paramètre %GAME_ID% s'utilise de la même manière que %GAME_NAME%. Il est remplacé par l'ID Steam du jeu pour lequel le bouton a été appelé. Exemple : https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. L'ID est demandé à Steam une seule fois par jeu, puis mis en cache. À cause de cette requête, le premier clic sur un tel bouton peut prendre un instant.",
        "Top Buttons style": "Style des boutons supérieurs",
        "Top Buttons style changer description": "Style CSS pour les boutons supérieurs. Vous pouvez le copier dans un autre éditeur, le modifier comme vous le souhaitez, puis le recoller ici.",
        "SettingsSavedSuccessfully": "Paramètres enregistrés avec succès !",
        "Name": "Nom",
        "Button Number": "Numéro du bouton",
        "Name for the drop-down menu section": "Nom de la section du menu déroulant",
        "Append after": "Insérer après",
        "After which element should the menu be inserted": "Après quel élément (par numéro) le menu déroulant avec boutons personnalisés doit être inséré",
        "Right click on game context menu buttons in drop down": "Boutons du menu contextuel au clic droit sur un jeu dans le menu déroulant",
        "Add right click on game context menu button in drop down": "Ajouter un bouton de clic droit sur un jeu dans le menu déroulant",
        "Game properties menu buttons": "Boutons du menu des propriétés du jeu",
        "Add game properties menu buttons": "Ajouter des boutons au menu des propriétés du jeu",
        "Top Buttons": "Boutons supérieurs",
        "Show name": "Afficher le nom",
        "Icon": "Icône",
        "Show icon": "Afficher l'icône",
        "Add top button": "Ajouter un bouton supérieur",
        "Store supernav buttons": "Boutons dans le menu 'Boutique' (Store supernav)",
        "Add store supernav buttons": "Ajouter un bouton au menu 'Boutique' (Store supernav)",
        "App page Buttons": "Boutons de la page du jeu",
        "Add app page button": "Ajouter un bouton à la page du jeu"
      },
    "Japanese": {
        "languageName": "日本語",
        "LanguageOfPlugin": "プラグインの言語",
        "SaveSettings": "設定を保存",
        "GameNameParameterTip": "* 印のあるボタンセクションでは、ボタン名と URL に %GAME_NAME% パラメータを使用できます。これはボタンが呼び出されたゲーム名に置き換えられます。例: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "ボタンに表示される名前",
        "ButtonShowNameTip": "ボタン名を表示しますか？",
        "ButtonIconTip": "ボタンに表示されるアイコンの URL",
        "ButtonShowIconTip": "ボタンのアイコンを表示しますか？",
        "ButtonPathToAppTip": "ボタンをクリックしたときに開く URL またはアプリパス（例: https://www.example.com または C:\\Program Files\\App\\app.exe）",
        "ButtonFormatGameNameTip": "%GAME_NAME% パラメータに挿入する際、ゲーム名を整形しますか？整形では空白とスラッシュが + に置き換えられ、ブラウザで URL を開くのに便利です。",
        "ButtonAddArrowIconTip": "ボタンに矢印アイコンを追加するかどうか",
        "DropdownMenuSettings": "ドロップダウンメニュー設定",
        "Right click on game context menu buttons": "ゲームを右クリックしたときのコンテキストメニューボタン",
        "Add right click on game context menu button": "ゲーム右クリックのコンテキストメニューボタンを追加",
        "FormatGameName": "ゲーム名を整形",
        "AddArrowIcon": "矢印アイコンを追加",
        "URL or App Path": "URL またはアプリパス",
        "delete this button": "このボタンを削除",
        "Add Button": "ボタンを追加",
        "EnableButton": "ボタンを有効化",
        "EnableButtonTip": "無効にすると、このボタンは Steam のインターフェースに追加されません",
        "ImportSettings": "設定をインポート",
        "ImportSettingsTip": "以前にエクスポートした JSON ファイルからすべての設定を読み込みます",
        "ExportSettings": "設定をエクスポート",
        "ExportSettingsTip": "現在のすべての設定を JSON ファイルに保存します",
        "ResetSettings": "設定をリセット",
        "ResetSettingsTip": "すべての設定を初期値に戻します",
        "Confirm": "確認",
        "Cancel": "キャンセル",
        "ConfirmDeleteButtonTitle": "削除の確認",
        "ConfirmDeleteButtonDescription": "ボタン %BUTTON_NUMBER%「%BUTTON_NAME%」を削除してもよろしいですか？この操作は元に戻せません。",
        "ConfirmResetSettingsTitle": "設定リセットの確認",
        "ConfirmResetSettingsDescription": "すべての設定を既定値にリセットしてもよろしいですか？すべてのボタンが既定のセットに置き換えられます。この操作は元に戻せません。",
        "ConfirmImportSettingsTitle": "設定インポートの確認",
        "ConfirmImportSettingsDescription": "選択したファイルから設定をインポートしてもよろしいですか？現在のボタンはすべて置き換えられます。この操作は元に戻せません。",
        "ImportSettingsError": "設定をインポートできませんでした: 有効な設定ファイルではありません",
        "SettingsAreSavedAutomatically": "すべての変更は自動的に保存されます",
        "GameIdCache": "ゲーム ID キャッシュ",
        "ClearGameIdCache": "ゲーム ID キャッシュを消去",
        "ClearGameIdCacheTip": "キャッシュされたゲーム ID をすべて削除します。%GAME_ID% パラメータを使うボタンを実行すると、再度 Steam に問い合わせます",
        "GameIdParameterTip": "%GAME_ID% パラメータは %GAME_NAME% と同じように使用できます。ボタンが呼び出されたゲームの Steam ID に置き換えられます。例: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/。ID はゲームごとに一度だけ Steam に問い合わせ、その後キャッシュされます。 そのため、このようなボタンの初回クリックはすぐに反応しないことがあります。",
        "Top Buttons style": "上部ボタンのスタイル",
        "Top Buttons style changer description": "上部ボタン用の CSS スタイルです。別のエディタにコピーして自由に編集し、ここに貼り戻せます。",
        "SettingsSavedSuccessfully": "設定を保存しました！",
        "Name": "名前",
        "Button Number": "ボタン番号",
        "Name for the drop-down menu section": "ドロップダウンメニューセクション名",
        "Append after": "次の後に挿入",
        "After which element should the menu be inserted": "カスタムボタン付きドロップダウンメニューをどの要素（番号）の後に挿入するか",
        "Right click on game context menu buttons in drop down": "ドロップダウン内のゲーム右クリックコンテキストメニューボタン",
        "Add right click on game context menu button in drop down": "ドロップダウン内にゲーム右クリックコンテキストメニューボタンを追加",
        "Game properties menu buttons": "ゲームのプロパティメニューボタン",
        "Add game properties menu buttons": "ゲームのプロパティメニューボタンを追加",
        "Top Buttons": "上部ボタン",
        "Show name": "名前を表示",
        "Icon": "アイコン",
        "Show icon": "アイコンを表示",
        "Add top button": "上部ボタンを追加",
        "Store supernav buttons": "「ストア」メニューのボタン（Store supernav）",
        "Add store supernav buttons": "「ストア」メニュー（Store supernav）にボタンを追加",
        "App page Buttons": "ゲームページのボタン",
        "Add app page button": "ゲームページにボタンを追加"
      },
    "Korean": {
        "languageName": "한국어",
        "LanguageOfPlugin": "플러그인 언어",
        "SaveSettings": "설정 저장",
        "GameNameParameterTip": "* 표시가 있는 버튼 섹션에서는 버튼 이름과 URL에 %GAME_NAME% 매개변수를 사용할 수 있습니다. 이 값은 버튼이 호출된 게임 이름으로 바뀝니다. 예: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "버튼에 표시될 이름",
        "ButtonShowNameTip": "버튼 이름을 표시할까요?",
        "ButtonIconTip": "버튼에 표시될 아이콘 URL",
        "ButtonShowIconTip": "버튼 아이콘을 표시할까요?",
        "ButtonPathToAppTip": "버튼을 클릭할 때 열 URL 또는 앱 경로(예: https://www.example.com 또는 C:\\Program Files\\App\\app.exe)",
        "ButtonFormatGameNameTip": "게임 이름을 %GAME_NAME% 매개변수에 넣을 때 형식화가 필요한가요? 형식화는 공백과 슬래시를 +로 바꾸어 브라우저에서 URL을 열기 쉽게 합니다.",
        "ButtonAddArrowIconTip": "버튼에 화살표 아이콘을 추가할지 여부",
        "DropdownMenuSettings": "드롭다운 메뉴 설정",
        "Right click on game context menu buttons": "게임 우클릭 컨텍스트 메뉴 버튼",
        "Add right click on game context menu button": "게임 우클릭 컨텍스트 메뉴 버튼 추가",
        "FormatGameName": "게임 이름 형식화",
        "AddArrowIcon": "화살표 아이콘 추가",
        "URL or App Path": "URL 또는 앱 경로",
        "delete this button": "이 버튼 삭제",
        "Add Button": "버튼 추가",
        "EnableButton": "버튼 활성화",
        "EnableButtonTip": "비활성화하면 이 버튼은 Steam 인터페이스에 추가되지 않습니다",
        "ImportSettings": "설정 가져오기",
        "ImportSettingsTip": "이전에 내보낸 JSON 파일에서 모든 설정을 불러옵니다",
        "ExportSettings": "설정 내보내기",
        "ExportSettingsTip": "현재 모든 설정을 JSON 파일로 저장합니다",
        "ResetSettings": "설정 초기화",
        "ResetSettingsTip": "모든 설정을 기본값으로 되돌립니다",
        "Confirm": "확인",
        "Cancel": "취소",
        "ConfirmDeleteButtonTitle": "삭제 확인",
        "ConfirmDeleteButtonDescription": "버튼 %BUTTON_NUMBER% '%BUTTON_NAME%'을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "ConfirmResetSettingsTitle": "설정 초기화 확인",
        "ConfirmResetSettingsDescription": "모든 설정을 기본값으로 초기화하시겠습니까? 모든 버튼이 기본 세트로 대체됩니다. 이 작업은 되돌릴 수 없습니다.",
        "ConfirmImportSettingsTitle": "설정 가져오기 확인",
        "ConfirmImportSettingsDescription": "선택한 파일에서 설정을 가져오시겠습니까? 현재 모든 버튼이 대체됩니다. 이 작업은 되돌릴 수 없습니다.",
        "ImportSettingsError": "설정을 가져오지 못했습니다: 올바른 설정 파일이 아닙니다",
        "SettingsAreSavedAutomatically": "모든 변경 사항은 자동으로 저장됩니다",
        "GameIdCache": "게임 ID 캐시",
        "ClearGameIdCache": "게임 ID 캐시 지우기",
        "ClearGameIdCacheTip": "캐시된 게임 ID를 모두 삭제합니다. %GAME_ID% 매개변수를 사용하는 버튼을 실행하면 Steam에 다시 요청합니다",
        "GameIdParameterTip": "%GAME_ID% 매개변수는 %GAME_NAME%과 같은 방식으로 사용할 수 있습니다. 버튼이 호출된 게임의 Steam ID로 바뀝니다. 예: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. ID는 게임마다 한 번만 Steam에 요청한 후 캐시됩니다. 이 요청 때문에 해당 버튼의 첫 클릭은 바로 반응하지 않을 수 있습니다.",
        "Top Buttons style": "상단 버튼 스타일",
        "Top Buttons style changer description": "상단 버튼용 CSS 스타일입니다. 다른 편집기로 복사해 원하는 대로 수정한 후 다시 붙여넣을 수 있습니다.",
        "SettingsSavedSuccessfully": "설정이 성공적으로 저장되었습니다!",
        "Name": "이름",
        "Button Number": "버튼 번호",
        "Name for the drop-down menu section": "드롭다운 메뉴 섹션 이름",
        "Append after": "다음 뒤에 추가",
        "After which element should the menu be inserted": "커스텀 버튼이 있는 드롭다운 메뉴를 몇 번째 요소 뒤에 삽입할지",
        "Right click on game context menu buttons in drop down": "드롭다운 내부의 게임 우클릭 컨텍스트 메뉴 버튼",
        "Add right click on game context menu button in drop down": "드롭다운 내부에 게임 우클릭 컨텍스트 메뉴 버튼 추가",
        "Game properties menu buttons": "게임 속성 메뉴 버튼",
        "Add game properties menu buttons": "게임 속성 메뉴 버튼 추가",
        "Top Buttons": "상단 버튼",
        "Show name": "이름 표시",
        "Icon": "아이콘",
        "Show icon": "아이콘 표시",
        "Add top button": "상단 버튼 추가",
        "Store supernav buttons": "'상점' 메뉴의 버튼 (Store supernav)",
        "Add store supernav buttons": "'상점' 메뉴(Store supernav)에 버튼 추가",
        "App page Buttons": "게임 페이지 버튼",
        "Add app page button": "게임 페이지 버튼 추가"
      },
    "Turkish": {
        "languageName": "Türkçe",
        "LanguageOfPlugin": "Eklenti dili",
        "SaveSettings": "Ayarları kaydet",
        "GameNameParameterTip": "* işaretiyle belirtilen düğme bölümlerinde, düğme adında ve URL'de %GAME_NAME% parametresi kullanılabilir. Bu değer, düğmenin çağrıldığı oyunun adıyla değiştirilir. Örneğin: https://www.google.com/search?q=%GAME_NAME% -> https://www.google.com/search?q=Subnautica",
        "ButtonNameTip": "Düğmede gösterilecek ad",
        "ButtonShowNameTip": "Düğme adı gösterilsin mi?",
        "ButtonIconTip": "Düğmede gösterilecek simgenin URL'si",
        "ButtonShowIconTip": "Düğme simgesi gösterilsin mi?",
        "ButtonPathToAppTip": "Düğmeye tıklandığında açılacak URL veya uygulama yolu (ör. https://www.example.com veya C:\\Program Files\\App\\app.exe)",
        "ButtonFormatGameNameTip": "Oyun adı %GAME_NAME% parametresine eklenirken biçimlendirilsin mi? Biçimlendirme boşlukları ve eğik çizgileri + ile değiştirir; bu, URL'leri tarayıcıda açmak için uygundur.",
        "ButtonAddArrowIconTip": "Düğmeye ok simgesi eklenip eklenmeyeceği",
        "DropdownMenuSettings": "Açılır menü ayarları",
        "Right click on game context menu buttons": "Oyuna sağ tıklama bağlam menüsü düğmeleri",
        "Add right click on game context menu button": "Oyuna sağ tıklama bağlam menüsüne düğme ekle",
        "FormatGameName": "Oyun adını biçimlendir",
        "AddArrowIcon": "Ok simgesi ekle",
        "URL or App Path": "URL veya uygulama yolu",
        "delete this button": "bu düğmeyi sil",
        "Add Button": "Düğme ekle",
        "EnableButton": "Düğmeyi etkinleştir",
        "EnableButtonTip": "Devre dışı bırakılırsa bu düğme Steam arayüzüne eklenmez",
        "ImportSettings": "Ayarları içe aktar",
        "ImportSettingsTip": "Daha önce dışa aktarılmış bir JSON dosyasından tüm ayarları yükle",
        "ExportSettings": "Ayarları dışa aktar",
        "ExportSettingsTip": "Mevcut tüm ayarları bir JSON dosyasına kaydet",
        "ResetSettings": "Ayarları sıfırla",
        "ResetSettingsTip": "Tüm ayarları varsayılan değerlerine sıfırla",
        "Confirm": "Onayla",
        "Cancel": "İptal",
        "ConfirmDeleteButtonTitle": "Silmeyi onayla",
        "ConfirmDeleteButtonDescription": "%BUTTON_NUMBER% numaralı '%BUTTON_NAME%' düğmesini silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
        "ConfirmResetSettingsTitle": "Sıfırlamayı onayla",
        "ConfirmResetSettingsDescription": "Tüm ayarları varsayılana sıfırlamak istediğinize emin misiniz? Tüm düğmeleriniz varsayılan setle değiştirilecek. Bu işlem geri alınamaz.",
        "ConfirmImportSettingsTitle": "İçe aktarmayı onayla",
        "ConfirmImportSettingsDescription": "Ayarları seçilen dosyadan içe aktarmak istediğinize emin misiniz? Mevcut tüm düğmeleriniz değiştirilecek. Bu işlem geri alınamaz.",
        "ImportSettingsError": "Ayarlar içe aktarılamadı: dosya geçerli bir ayar dosyası değil",
        "SettingsAreSavedAutomatically": "Tüm değişiklikler otomatik olarak kaydedilir",
        "GameIdCache": "Oyun kimliği önbelleği",
        "ClearGameIdCache": "Oyun kimliği önbelleğini temizle",
        "ClearGameIdCacheTip": "Önbelleğe alınmış tüm oyun kimliklerini sil. %GAME_ID% parametresini kullanan bir düğme çalıştırıldığında Steam'den yeniden istenir",
        "GameIdParameterTip": "%GAME_ID% parametresi %GAME_NAME% ile aynı şekilde kullanılabilir. Düğmenin çağrıldığı oyunun Steam kimliği ile değiştirilir. Örneğin: https://steamdb.info/app/%GAME_ID%/ -> https://steamdb.info/app/1091500/. Kimlik her oyun için Steam'den bir kez istenir ve ardından önbelleğe alınır. Bu istek nedeniyle böyle bir düğmeye yapılan ilk tıklama hemen çalışmayabilir.",
        "Top Buttons style": "Üst düğmeler stili",
        "Top Buttons style changer description": "Üst düğmeler için CSS stili. Bunu başka bir düzenleyiciye kopyalayabilir, istediğiniz gibi değiştirebilir ve buraya geri yapıştırabilirsiniz.",
        "SettingsSavedSuccessfully": "Ayarlar başarıyla kaydedildi!",
        "Name": "Ad",
        "Button Number": "Düğme numarası",
        "Name for the drop-down menu section": "Açılır menü bölümü adı",
        "Append after": "Sonrasına ekle",
        "After which element should the menu be inserted": "Özel düğmeli açılır menü hangi öğeden (numara olarak) sonra eklenmeli",
        "Right click on game context menu buttons in drop down": "Açılır menü içindeki oyuna sağ tıklama bağlam menüsü düğmeleri",
        "Add right click on game context menu button in drop down": "Açılır menü içine oyuna sağ tıklama bağlam menüsü düğmesi ekle",
        "Game properties menu buttons": "Oyun özellikleri menüsü düğmeleri",
        "Add game properties menu buttons": "Oyun özellikleri menüsüne düğme ekle",
        "Top Buttons": "Üst düğmeler",
        "Show name": "Adı göster",
        "Icon": "Simge",
        "Show icon": "Simgeyi göster",
        "Add top button": "Üst düğme ekle",
        "Store supernav buttons": "'Mağaza' menüsündeki düğmeler (Store supernav)",
        "Add store supernav buttons": "'Mağaza' menüsüne (Store supernav) düğme ekle",
        "App page Buttons": "Oyun sayfası düğmeleri",
        "Add app page button": "Oyun sayfasına düğme ekle"
      }
};